version: '3.9'

services:
  roll_d_n_rust:
    container_name: roll_d_n_rust
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'